name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies & Build
        working-directory: /var/www/html/quiz-quest-BE
        run: |
          npm install
          npm run build

      - name: Install PM2 and Restart Application
        run: |
          npm install -g pm2
          pm2 restart quiz-backend
